# Generated by Django 3.0.2 on 2020-01-06 08:19

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Tên Khoá học')),
                ('brief', models.TextField(verbose_name='Tóm Tắt')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', filebrowser.fields.FileBrowseField(blank=True, max_length=5000, verbose_name='Image')),
                ('overview', tinymce.models.HTMLField(verbose_name='Nội Dung')),
                ('featured', models.BooleanField(default=True, verbose_name='Hiện thị')),
            ],
            options={
                'verbose_name_plural': 'Khoá Học',
            },
        ),
        migrations.CreateModel(
            name='Course_Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Tên Khoá học')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chap', to='courses.Course')),
            ],
            options={
                'verbose_name_plural': 'Lộ trình',
            },
        ),
        migrations.CreateModel(
            name='Course_Chap_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Tên video')),
                ('type_video', models.CharField(choices=[('GD', 'Google Drive'), ('YT', 'Youtube'), ('IR', 'iframe')], max_length=2000, verbose_name='Kiểu video')),
                ('url', models.CharField(max_length=501, verbose_name='URL')),
                ('url_api', models.CharField(blank=True, editable=False, max_length=2000)),
                ('url_thumb', models.CharField(blank=True, editable=False, max_length=50)),
                ('time_video_mili', models.IntegerField(blank=True, editable=False)),
                ('is_open_for_free', models.BooleanField(default=True)),
                ('course_chap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='courses.Course_Chapter')),
            ],
            options={
                'verbose_name_plural': 'Video Khoá Học',
            },
        ),
    ]
