# Generated by Django 3.0.2 on 2020-01-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course_chap_video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Video Khoá Học'},
        ),
        migrations.AlterModelOptions(
            name='course_chapter',
            options={'verbose_name': 'Lộ trình', 'verbose_name_plural': 'Lộ trình'},
        ),
    ]
