# Generated by Django 3.0.2 on 2020-01-17 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', filebrowser.fields.FileBrowseField(blank=True, max_length=5000, verbose_name='Avatar')),
                ('body', models.CharField(max_length=5000, verbose_name='Thông Tin Thêm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCat', models.CharField(max_length=5000, unique=True, verbose_name='Tên Thể Loai')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Ngày Tạo')),
                ('featured', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Thể Loại',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nhập tiêu đề', max_length=2000, verbose_name='Tiêu Đề')),
                ('summary', models.TextField(verbose_name='Tóm Tắt')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('content', tinymce.models.HTMLField(verbose_name='Nội Dung')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment_count', models.IntegerField(default=0, editable=False)),
                ('view_count', models.IntegerField(default=0, editable=False)),
                ('thumbnail', filebrowser.fields.FileBrowseField(blank=True, max_length=5000, verbose_name='Image')),
                ('featured', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Author')),
                ('categories', models.ManyToManyField(to='blogs.Category')),
            ],
            options={
                'verbose_name_plural': 'Tất Cả Bài Viết',
            },
        ),
        migrations.CreateModel(
            name='Reaction_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('love', models.IntegerField(default=0)),
                ('shocked', models.IntegerField(default=0)),
                ('angry', models.IntegerField(default=0)),
                ('crying', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction', to='blogs.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'React_Post',
                'verbose_name_plural': 'React_Posts',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.IntegerField(default=0, editable=False)),
                ('is_dislike', models.IntegerField(default=0, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blogs.Post')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rep', to='blogs.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bình Luận',
                'verbose_name_plural': 'Comments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Button_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000, verbose_name='Nội Dung')),
                ('button', models.CharField(choices=[('DW', 'Downloads'), ('LK', 'Links')], max_length=2000, verbose_name='Button')),
                ('link', models.CharField(max_length=2000, verbose_name='Đường Dẫn')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='button', to='blogs.Post')),
            ],
            options={
                'verbose_name': 'Button',
                'verbose_name_plural': 'Button',
            },
        ),
    ]
